### ISSUE TITLE
[feature request] export `InheritedGoRouter`

### ISSUE THREAD

**Issue by aoatmon** [csells/go_router#228]
[InheritedGoRouter](https://github.com/csells/go_router/blob/main/go_router/lib/src/inherited_go_router.dart)

is not exported in https://github.com/csells/go_router/blob/main/go_router/lib/go_router.dart

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

///! https://github.com/csells/go_router/blob/main/go_router/lib/src/inherited_go_router.dart
void main() {
  runApp(const InheritedGoRouter());
}

```

```yaml
name: inherited_gorouter_issue
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
```

```console
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.0)
[✓] Connected device (3 available)

• No issues found!
```
